name: Lint

on: [push, pull_request]
     

jobs:
  test-lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install .[dev]
    - name: Run ruff check and format
      run: |
        ruff check lockpy
        ruff format --check lockpy
    - name: Run mypy
      run: |
        mypy lockpy
